### ISSUE TITLE
Java's URL object does not recognize 'wss' scheme.

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/ofmeet-openfire-plugin#3]
When trying to run OFMeet with the websockets plugin, this error is logged:

```2017.06.01 20:59:50 ERROR [Jetty-QTP-BOSH-315]: org.jivesoftware.openfire.plugin.ofmeet.ConfigServlet - OFMeetConfig doGet Error
java.net.MalformedURLException: unknown protocol: wss
        at java.net.URL.<init>(URL.java:421)
        at java.net.URL.<init>(URL.java:310)
        at org.jivesoftware.openfire.plugin.ofmeet.ConfigServlet.getMostPreferredConnectionURL(ConfigServlet.java:282)
        at org.jivesoftware.openfire.plugin.ofmeet.ConfigServlet.doGet(ConfigServlet.java:190)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
        at org.jivesoftware.openfire.plugin.ofmeet.JitsiMeetRedirectFilter.doFilter(JitsiMeetRedirectFilter.java:96)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by guusdk** [comment]
This is fixed in 4428d3137cfbf3652f69735ae9cfb98d54681e4d
